2017-03-31T04:01:59.982506+00:00 heroku[web.1]: Starting process with command `target/universal/stage/bin/bigbob -Dhttp.port=28454 -DapplyEvolutions.default=true -Ddb.default.driver=org.postgresql.Driver -Ddb.default.url=postgres://ateuzcehjscmge:149e0acf1f2c52439e2d2e464ff1114da7d1df13b890bfbf59fbf27343e615e6@ec2-176-34-113-15.eu-west-1.compute.amazonaws.com:5432/d93d063h9a7tvl`
2017-03-31T04:02:01.666775+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2017-03-31T04:02:01.759391+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx350m -Xss512k -Dfile.encoding=UTF-8
2017-03-31T04:02:02.130175+00:00 app[web.1]: Play server process ID is 4
2017-03-31T04:02:03.178971+00:00 app[web.1]: [[37minfo[0m] play - database [default] connected at jdbc:postgresql://ec2-176-34-113-15.eu-west-1.compute.amazonaws.com:5432/d93d063h9a7tvl
2017-03-31T04:02:05.170302+00:00 app[web.1]: [[37minfo[0m] play - Listening for HTTP on /0:0:0:0:0:0:0:0:28454
2017-03-31T04:02:05.035984+00:00 app[web.1]: [[37minfo[0m] application - Using S3 Bucket: heroku-bob-saver-from-bigbob-to-littlebob-with-fatbob-v.01
2017-03-31T04:02:05.041160+00:00 app[web.1]: [[37minfo[0m] play - Application started (Prod)
2017-03-31T04:02:05.267313+00:00 heroku[web.1]: State changed from starting to up
2017-03-31T04:02:23.290821+00:00 app[web.1]: [[31merror[0m] play - Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:ERROR: relation "s3file" does not exist
2017-03-31T04:02:23.290843+00:00 app[web.1]: Query was:
2017-03-31T04:02:23.290841+00:00 app[web.1]:   Position: 57 
2017-03-31T04:02:23.290845+00:00 app[web.1]: 
2017-03-31T04:02:23.290842+00:00 app[web.1]: Bind values:[] 
2017-03-31T04:02:23.290846+00:00 app[web.1]: 
2017-03-31T04:02:23.309010+00:00 app[web.1]: [[31merror[0m] application - 
2017-03-31T04:02:23.290844+00:00 app[web.1]: select t0.id as c0, t0.bucket as c1, t0.name as c2 from s3file t0 
2017-03-31T04:02:23.309013+00:00 app[web.1]: 
2017-03-31T04:02:23.309015+00:00 app[web.1]: 
2017-03-31T04:02:23.309014+00:00 app[web.1]: ! @73g8mh7c4 - Internal server error, for (GET) [/] ->
2017-03-31T04:02:23.309016+00:00 app[web.1]: play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:ERROR: relation "s3file" does not exist
2017-03-31T04:02:23.309018+00:00 app[web.1]: Bind values:[] 
2017-03-31T04:02:23.309020+00:00 app[web.1]: select t0.id as c0, t0.bucket as c1, t0.name as c2 from s3file t0 
2017-03-31T04:02:23.309017+00:00 app[web.1]:   Position: 57 
2017-03-31T04:02:23.309021+00:00 app[web.1]: 
2017-03-31T04:02:23.309019+00:00 app[web.1]: Query was:
2017-03-31T04:02:23.309021+00:00 app[web.1]: ]]
2017-03-31T04:02:23.309022+00:00 app[web.1]: 	at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:23.309023+00:00 app[web.1]: 	at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:23.309027+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:23.309028+00:00 app[web.1]:   Position: 57 
2017-03-31T04:02:23.309029+00:00 app[web.1]: Bind values:[] 
2017-03-31T04:02:23.309029+00:00 app[web.1]: Query was:
2017-03-31T04:02:23.309030+00:00 app[web.1]: select t0.id as c0, t0.bucket as c1, t0.name as c2 from s3file t0 
2017-03-31T04:02:23.309031+00:00 app[web.1]: 
2017-03-31T04:02:23.309025+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:23.309024+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:23.309027+00:00 app[web.1]: Caused by: javax.persistence.PersistenceException: Query threw SQLException:ERROR: relation "s3file" does not exist
2017-03-31T04:02:23.309026+00:00 app[web.1]: 	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.3.jar:na]
2017-03-31T04:02:23.309033+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:23.309035+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:23.309031+00:00 app[web.1]: 
2017-03-31T04:02:23.309036+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:23.309036+00:00 app[web.1]: Caused by: org.postgresql.util.PSQLException: ERROR: relation "s3file" does not exist
2017-03-31T04:02:23.309032+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:23.309033+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:23.309037+00:00 app[web.1]:   Position: 57
2017-03-31T04:02:23.309034+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:23.309038+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:23.309040+00:00 app[web.1]: 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:23.309040+00:00 app[web.1]: 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:23.309038+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:23.309039+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:23.309041+00:00 app[web.1]: 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:23.338368+00:00 heroku[router]: at=info method=GET path="/" host=bob-saver.herokuapp.com request_id=732c2e34-0c2e-4c29-8a52-999d2e73b594 fwd="80.237.124.254" dyno=web.1 connect=0ms service=657ms status=500 bytes=2060 protocol=https
2017-03-31T04:02:33.848726+00:00 app[web.1]: [[31merror[0m] play - Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:ERROR: relation "s3file" does not exist
2017-03-31T04:02:33.848742+00:00 app[web.1]:   Position: 57 
2017-03-31T04:02:33.848743+00:00 app[web.1]: Bind values:[] 
2017-03-31T04:02:33.851170+00:00 app[web.1]: [[31merror[0m] application - 
2017-03-31T04:02:33.848744+00:00 app[web.1]: Query was:
2017-03-31T04:02:33.851175+00:00 app[web.1]: 
2017-03-31T04:02:33.848745+00:00 app[web.1]: select t0.id as c0, t0.bucket as c1, t0.name as c2 from s3file t0 
2017-03-31T04:02:33.851176+00:00 app[web.1]: play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:ERROR: relation "s3file" does not exist
2017-03-31T04:02:33.848745+00:00 app[web.1]: 
2017-03-31T04:02:33.848746+00:00 app[web.1]: 
2017-03-31T04:02:33.851174+00:00 app[web.1]: ! @73g8mhn22 - Internal server error, for (GET) [/] ->
2017-03-31T04:02:33.851173+00:00 app[web.1]: 
2017-03-31T04:02:33.851180+00:00 app[web.1]: ]]
2017-03-31T04:02:33.851176+00:00 app[web.1]:   Position: 57 
2017-03-31T04:02:33.851177+00:00 app[web.1]: Bind values:[] 
2017-03-31T04:02:33.851178+00:00 app[web.1]: Query was:
2017-03-31T04:02:33.851179+00:00 app[web.1]: select t0.id as c0, t0.bucket as c1, t0.name as c2 from s3file t0 
2017-03-31T04:02:33.851179+00:00 app[web.1]: 
2017-03-31T04:02:33.855147+00:00 heroku[router]: at=info method=GET path="/" host=bob-saver.herokuapp.com request_id=e35b2384-d036-4b54-bb84-91c8fbde109a fwd="80.237.124.254" dyno=web.1 connect=0ms service=18ms status=500 bytes=2060 protocol=https
2017-03-31T04:02:33.851183+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:33.851184+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$3.apply(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:33.851181+00:00 app[web.1]: 	at play.api.Application$class.handleError(Application.scala:293) ~[com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:33.851182+00:00 app[web.1]: 	at play.api.DefaultApplication.handleError(Application.scala:399) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:33.851188+00:00 app[web.1]: Query was:
2017-03-31T04:02:33.851184+00:00 app[web.1]: 	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.3.jar:na]
2017-03-31T04:02:33.851185+00:00 app[web.1]: 	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:268) [com.typesafe.play.play_2.10-2.2.6.jar:2.2.6]
2017-03-31T04:02:33.851186+00:00 app[web.1]: Caused by: javax.persistence.PersistenceException: Query threw SQLException:ERROR: relation "s3file" does not exist
2017-03-31T04:02:33.851190+00:00 app[web.1]: 
2017-03-31T04:02:33.851187+00:00 app[web.1]:   Position: 57 
2017-03-31T04:02:33.851190+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:790) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:33.851187+00:00 app[web.1]: Bind values:[] 
2017-03-31T04:02:33.851188+00:00 app[web.1]: select t0.id as c0, t0.bucket as c1, t0.name as c2 from s3file t0 
2017-03-31T04:02:33.851189+00:00 app[web.1]: 
2017-03-31T04:02:33.851195+00:00 app[web.1]: Caused by: org.postgresql.util.PSQLException: ERROR: relation "s3file" does not exist
2017-03-31T04:02:33.851191+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:767) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:33.851192+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:202) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:33.851193+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:33.851194+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findList(OrmQueryRequest.java:265) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:33.851197+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:33.851194+00:00 app[web.1]: 	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1460) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.2.2.jar:na]
2017-03-31T04:02:33.851198+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:33.851196+00:00 app[web.1]:   Position: 57
2017-03-31T04:02:33.851196+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:33.851199+00:00 app[web.1]: 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:33.851199+00:00 app[web.1]: 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
2017-03-31T04:02:33.851200+00:00 app[web.1]: 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:273) ~[postgresql.postgresql-9.1-901-1.jdbc4.jar:na]
